# -*- coding: utf-8 -*-
"""EDA-Case-Study-15-02-26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TtVaQwYLwfB2dPh_OQUSmCoq8CJB0JFh
"""

# Dataset link -> https://drive.google.com/file/d/1s-k6UuNoISCD1vBeb0c7c7CgeSHYeCm8/view

# Load the data ->

# time -> 8:20

import pandas as pd

df = pd.read_csv("/content/vgsales (1).csv")

df

df.shape

# EDA (Exploratory Data Analysis) -> Try to understand about the data -> detection/analyze
# -> Detect null values, dupicates, outliers

# Data Preprocessing ->
# -> Handle the null values, duplicates, outliers

# Drop the Rank column

# time -> 8:33

df.columns

df.drop(columns=["Rank"], inplace=True)

df.info()

df.head()

# Null Values ->
# handle the null values...

# time -> 8:46

df.info()

df.isnull().sum()

# mean()
# publisher-> mode()/unknown

# df["year"] -> mean
# df["Publisher"] -> mode

# int -> mean
# obj -> mode

for col in df.columns:
  if(df[col].dtype == "object"):
    df[col] = df[col].fillna(df[col].mode()[0])
  else:
    df[col] = df[col].fillna(df[col].mean())

df["Publisher"].mode()[0]

df["Year"].mean()

df.isnull().sum()

# Duplicates >

# time -> 9:05

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

# Outliers ->

# i) Detect the outliers
# ii) Handle the outliers -> IQR

# time ->

import matplotlib.pyplot as plt

for col in df.columns:
  if(df[col].dtype != "object"):
    plt.boxplot(df[col])
    plt.title(col)
    plt.show()

# Handle the null values and duplicates
# Detectiong outliers

